#!/usr/bin/env bash

set -euo pipefail

channel="release"
if [[ "${1:-}" == "debug" ]]; then
	shift
	channel="debug"
fi

genbin="_generator/target/$channel/generator"

if [[ "$channel" == "debug" ]]; then
	cd _generator
	cargo build
	cd ..
elif [[ ! -x "$genbin" ]]; then
	cd _generator
	cargo build --release
	cd ..
fi

if [[ ! -x "$genbin" ]]; then
	echo "Did not manage to build the generator !?" >&2
	exit 42
fi

exec "$genbin" $@ --config generators.yml
