#!/usr/bin/env bash

set -euo pipefail

channel="release"
if [[ "${1:-}" == "debug" ]]; then
	shift
	channel="debug"
fi

cd _generator
if [[ "$channel" == "debug" ]]; then
	cargo build
else
	cargo build --release
fi
cd ..

exec "_generator/target/$channel/generator" $@ --config generators.yml
