#!/usr/bin/env bash

set -euo pipefail

app="${1:-}"
version="${2:-}"

if [[ -z "$app" ]]; then
	echo "Usage: $0 APP [VERSION]"
	exit 1
fi

if [[ -z "$version" ]]; then
	# TODO:
	version=$(_bin/generator latest-version --app "$app")
fi

dlpath="downloads/$app/$version"
metapath="$dlpath/meta.json"
pagepath="$dlpath/index.html"

make_meta() {
	mkdir -p "$dlpath"
	_bin/generator release-meta --app "$app" --version "$version"
}

make_page() {
	mkdir -p "$dlpath"
	_bin/generator release-page --meta "$metapath"
}

if [[ -f "$metapath" ]]; then
	echo -n "$metapath exists, overwrite? [Yn] "
	read confirm
	if [[ "$confirm" != n* ]]; then
		make_meta
	fi
else
	make_meta
fi

if [[ -f "$pagepath" ]]; then
	echo -n "$pagepath exists, overwrite? [Yn] "
	read confirm
	if [[ "$confirm" != n* ]]; then
		make_page
	fi
else
	make_page
fi
