name: Deploy
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install mdbook
        run: |
          set -exo pipefail
          curl -L https://github.com/alsuren/cargo-quickinstall/releases/download/mdbook-0.4.15-x86_64-unknown-linux-gnu/mdbook-0.4.15-x86_64-unknown-linux-gnu.tar.gz | tar -xzf - -C ~/.cargo/bin
          curl -L https://github.com/alsuren/cargo-quickinstall/releases/download/mdbook-linkcheck-0.7.6-x86_64-unknown-linux-gnu/mdbook-linkcheck-0.7.6-x86_64-unknown-linux-gnu.tar.gz | tar -xzf - -C ~/.cargo/bin

      - run: mdbook build
      - uses: Cecilapp/GitHub-Pages-deploy@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          email: felix@passcod.name
          build_dir: book/html
          branch: gh-pages
          jekyll: no
